# Generated by Django 4.1.1 on 2022-09-22 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Platera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platera', models.CharField(max_length=50)),
                ('kopurua', models.IntegerField()),
            ],
        ),
    ]
