# Generated by Django 4.1.1 on 2022-10-11 10:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('langileak', '0002_sukaldaria_delete_langilea'),
        ('platerak', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='platera',
            name='sukaldaria',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='langileak.sukaldaria'),
        ),
    ]
