# Generated by Django 4.1.1 on 2022-10-07 09:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('platerak', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Langilea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('izena', models.CharField(max_length=50)),
                ('platera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='platerak.platera')),
            ],
        ),
    ]
