# Generated by Django 4.1.1 on 2022-10-11 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('langileak', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sukaldaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('izena', models.CharField(max_length=50)),
                ('abizena', models.CharField(max_length=50)),
            ],
        ),
        migrations.DeleteModel(
            name='Langilea',
        ),
    ]
